### ISSUE TITLE
Datart_cz - both actor and extension do not take coupon price as currentPrice

### ISSUE THREAD

**Issue by MartinaGelnerova** [topmonks/hlidac-shopu#2882]
example: https://www.datart.cz/espresso-de-longhi-magnifica-s-ecam-22-112-b-cerne.html

![Image](https://github.com/user-attachments/assets/0bd79ec7-0b1e-4322-92f6-2139cccfff2b)

**Comment by MartinaGelnerova** [comment]
Current example: https://www.datart.cz/elektricka-kolobezka-sencor-scooter-s80-cerna.html

**Comment by vaclav-slavik** [comment]
@MartinaGelnerova Ready for testing once the next extension release is out.

**Comment by MartinaGelnerova** [comment]
@vaclav-slavik still some issues with this shop

1) coupon price
extension takes correct currentPrice BUT wrong originalPrice
(there is an issue with scraped currentPrice, but I will deal with this in separete GH issue)
example: https://www.datart.cz/elektricka-kolobezka-sencor-scooter-s80-cerna.html
- the originalPrice = crossed out refPrice = 19.999
<img width="3433" height="1344" alt="Image" src="https://github.com/user-attachments/assets/3e11ef56-82c3-4b9b-9ac8-65a2282c0f26" />

2) Now the extension misses the originalPrice with standard discount - please correct 🙏
example: https://www.datart.cz/mys-lorgar-msa10w-lrg-msa10w-wh-bila
- the originalPrice = crossed out refPrice = 1.399
<img width="3445" height="1773" alt="Image" src="https://github.com/user-attachments/assets/73157952-67e4-46e6-9270-248f02e356a5" />

**Comment by vaclav-slavik** [comment]
Follow-up fixed in 2.4.8 — see [`ee55630d8`](https://github.com/topmonks/hlidac-shopu/commit/ee55630d8). Datart shipped an EU-Omnibus reference-price layout. The crossed-out refPrice now lives in `.product-price-before .cut-price--lessOrEqual`; the old `.product-price .cut-price del` no longer matches (returns `null` → "missing originalPrice"). The coupon special-case was also wrong — it returned the regular non-coupon price as the originalPrice, but `data-price-value` already reflects coupon discounts, so a single Omnibus-based selector covers both cases. The visually-hidden "Nejnižší cena za posledních 30 dní" label inside `.sr-only` is stripped before parsing so the "30" doesn't poison the regex.

**Comment by MartinaGelnerova** [comment]
ad 2) extension misses the originalPrice with standard discount - please correct
- fixed 👍 

ad 1) coupon price: extension takes correct currentPrice BUT wrong originalPrice
NOT FIXED, please correct @vaclav-slavik 
- we save the product with coupon discount as it is not discounted at all
- we have the same issue with scraped data, but I will create a separate GHissue for that
- up-to-date example: https://www.datart.cz/rychlovarna-konvice-russell-hobbs-calm-27450-70-bila-zlata
- currentPrice: 2309 (the one with coupon), originalPrice: 3299 (the one stated as Nejnižší cena za posledních 30 dní:)

<img width="2286" height="1568" alt="Image" src="https://github.com/user-attachments/assets/fc8eabca-774b-4e8a-afb6-07bcc1cccd15" />

**Comment by vaclav-slavik** [comment]
@MartinaGelnerova Coupon case fixed in [`1f8543576`](https://github.com/topmonks/hlidac-shopu/commit/1f8543576). Root cause: Datart renamed the Omnibus reference-price CSS class (`.cut-price--lessOrEqual` → `.cut-price--strike`, and the variant differs by discount type — which is why coupon pages never matched). With the selector missing, `originalPrice` came out `null` and coupon products were saved as not discounted at all.

The scraper now anchors on the stable `.cut-price` wrapper regardless of the modifier variant. Verified live on datart.cz:

- your kettle example (meanwhile turned into a standard 20% discount): currentPrice 2629, originalPrice **3299** ✓
- another discounted product: 4990 / 5990 ✓
- non-discounted product: 7990 / null ✓ (no false originalPrice)

Note: there's no active coupon campaign on datart.cz right now, so I couldn't verify a live coupon product directly — but the failure was purely the renamed class, which the fix no longer depends on, and `data-price-value` (currentPrice) already reflects coupons as you confirmed. Ships with the next extension release — **ready for testing once it's out**, ideally on a product with an active coupon.

Also noting: datart.sk now redirects to nay.sk, so this applies to the CZ site only.

**Comment by vaclav-slavik** [comment]
@MartinaGelnerova **Please test only after the extension updates to 2.4.11** — Firefox already has it, Chrome is pending review. Ideally verify on a product with an active coupon campaign.

**Comment by zuzanalaubeova** [comment]
@vaclav-slavik @MartinaGelnerova This bug is still active, even if I have extension version 2.4.11. Coupon price is missing both in scraping and extension current price, see:

<img width="1762" height="897" alt="Image" src="https://github.com/user-attachments/assets/3d3953a6-46f7-4aa2-8e25-4729f968d886" />

**Comment by vaclav-slavik** [comment]
@zuzanalaubeova Released in **2.4.12**, ready for testing. Please test only after your extension shows version 2.4.12 (the widget's about page). Chrome and Firefox are both in store review right now and will update automatically once approved.
